### ISSUE TITLE
NotoSansOriya cannot place Nuktah on most characters

### ISSUE THREAD

**Issue by KazunariTsuboi** [notofonts/oriya#10]
### Font 
NotoSansOriya-*.ttf

### Where the font came from, and when
https://github.com/notofonts/noto-fonts/tree/76ab49e/hinted/ttf/NotoSansOriya
Date: 2021-11-02

### Font Version
Version 2.000
commit 76ab49e9a7036b461daec780ae062367473b3ef8

### OS name and version
Windows10 21H2 19044. 1706

### Application name and version
Google Chrome 103.0.5060.53（Official Build） （64 bit）

### Issue
Nukta could not be placed for various characters. "Nukta" anchor works only for a few glyphs associated with "dda" and "ddha", but other various characters, such as "ya", also require the same function.

### Character data
କ଼ ଯ଼

![image](https://user-images.githubusercontent.com/21096794/176369903-28aec74f-0526-4295-97ec-b4fca34d342a.png)

**Comment by simoncozens** [comment]
I've done what I can here, adding anchors at approximately the right positions. If a designer wants to go through and refine those positions, that would be helpful.
