### ISSUE TITLE
Noto Sans Oriya font family failing to render properly for Scribus and Firefox

### ISSUE THREAD

**Issue by psubhashish** [notofonts/oriya#17]
### Title 
Noto Sans Oriya font family failing to render properly for Scribus and Firefox

### Font 
The entire Noto Sans Oriya font family

### Where the font came from, and when
* Site: https://fonts.google.com/download?family=Noto%20Sans%20Oriya
* Date: 2023-03-23

### Font Version
  > * Mac - right mouse click on a font and try Preview to see version info.
  > * Win -- right mouse click on a font (Local Disc > Windows > Fonts) and see version info on Properties.
  > * Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.
Noto Sans Oriya 14.0d1e2 and 2.003 (both versions tested)

### OS name and version
  > This is especially important if the font came pre-installed.
MacOS Ventura 13.2.1 and Windows (issues detailed [here](https://github.com/notofonts/oriya/releases/tag/NotoSansOriya-v2.003)

### Application name and version
  > If the issue is observed using a specific app.
Scribus 1.5.8 on MacOS Ventura 13.2.1 (and also for Windows)

### Issue
  > Summarize the issue briefly -- one paragraph preferred

  1. As mentioned [here](https://bugs.scribus.net/view.php?id=16916), the Noto Sans Oriya font family, all the 36 fonts, were tested for Scribus (New document, Export as PDF) both in the text field and after exporting.
  2. Noto Sans Oriya failed to render properly both in the text field and after exporting. Another Google Fonts font, Anek Odia, rendered properly. Note that Noto Sans Oriya rendered fine on Brave v 1.49.128 and Firefox 111.0.1, both on MacOS Ventura 13.2.1 

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

Several screenshots already posted here at https://bugs.scribus.net/view.php?id=16916#c50053 showing the rendering issues

### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by simoncozens** [comment]
Unfortunately I'm finding the Scribus bug tracker intermittently failing for me ("Failed to establish a secure connection", "Connection reset", etc.)

When I did manage to see it, it referred to "the obsolete fonts from 2019".  Do the same problems occur with the current fonts (https://notofonts.github.io/oriya/)? Can you provide here the text sequences you used? I can't get them from the Scribus site at all now.

**Comment by simoncozens** [comment]
The issue here is fixed in the repository and in the fonts you can get [from here](https://notofonts.github.io/oriya/), but not (yet) on Google Fonts. This is because there is a separate problem with the variable font which is causing the width axis to not work; but I think the shaping is now correct.

**Comment by psubhashish** [comment]
This is good news. Thank you @simoncozens for the update. Though MacOS restricts replacing older versions of Noto Sans Oriya, a system font, and installing each .ttf file separately, I hope the future MacOS updates would include. But it's good that your team is aware of this issue and future release would reflect the fix. IDK if it's feasible for current and future designers to be aware of this issue. I suspect if other complex writing systems are also similarly affected.
