### ISSUE TITLE
Isn’t that overline too thin?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/oriya#18]
### Title 
0B55 Oriya sign Overline is probably too thin

### Font 
NotoSansOriya-Regular.ttf

### Where the font came from, and when
Site: this repo, latest release
Date: 2023-03-27

### Font Version
2.005

### OS name and version
Win10 22H2

### Application name and version
Qt 6.1.3, probably all apps

### Issue
0B55 Oriya sign Overline is probably too thin

### Character data
0B55 Oriya sign Overline

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/227934002-9ba86b7e-3ebc-4496-9f05-f61496951319.png)

**Comment by simoncozens** [comment]
Yeah, something went weird with the order of the masters here.

**Comment by Mercury13** [comment]
One more bug is seen here (did not test it though how they actually stick to letters): umlauts U, UU etc do not anchor to 25CC.

**Comment by Mercury13** [comment]
One more bug is seen here (did not test it though how they actually stick to letters): umlauts U, UU etc do not anchor to 25CC.

**Comment by Mercury13** [comment]
Strange things: thickness is just random at Thin, Regular and Black.
Absolute: Regular < Thin < Black.
Relative: Black < Regular < Thin.

**Comment by Mercury13** [comment]
Confused variable axes? I don’t think so.

**Comment by simoncozens** [comment]
I've fixed this with a rebuild with the latest toolchain, and sorting out some extraneous layers. The U vowel attachment to dotted circle appears to work fine.
<img width="195" alt="Screenshot 2023-10-25 at 15 12 08" src="https://github.com/notofonts/oriya/assets/106728/46a91c50-3649-43d3-9402-9f392a27d7f3">
