### ISSUE TITLE
Missing anchor points for nukta and virama

### ISSUE THREAD

**Issue by dscorbett** [notofonts/oriya#19]
### Font
NotoSansOriya-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/oriya/releases/tag/NotoSansOriya-v2.005
Date: 2023-03-27

### Font version
Version 2.005

### Issue
Anchor points are missing for nukta and virama for many base glyphs. The strings below are a small non-exhaustive sample.

### Character data
ବ଼
U+0B2C ORIYA LETTER BA
U+0B3C ORIYA SIGN NUKTA

ଡ଼୍
U+0B21 ORIYA LETTER DDA
U+0B3C ORIYA SIGN NUKTA
U+0B4D ORIYA SIGN VIRAMA

### Screenshot
![ବ଼ ଡ଼୍](https://user-images.githubusercontent.com/1124347/228018325-ce9db062-3f55-456d-800f-e7c229bd8ddc.png)

**Comment by simoncozens** [comment]
I think this was fixed by #23.
