### ISSUE TITLE
Vowels not connecting with RHA, RRA in NotoSansOriya

### ISSUE THREAD

**Issue by KazunariTsuboi** [notofonts/oriya#21]
### Title
Vowels not connecting with RHA, RRA in NotoSansOriya

### Font
NotoSansOriya-Regular.ttf

### Where the font came from, and when
Site: https://github.com/notofonts/oriya/releases/tag/NotoSansOriya-v2.005
Date: 2023-03-27

### Font version
Version 2.005

### Issue
In NotoSansOriya, when RHA, RRA (DHA, DDHA + Nukta) + Vowel, vowels do not connect.

![image](https://github.com/notofonts/oriya/assets/21096794/9cd821c6-f543-43d9-9208-163d610e3bff)

### Character data
ଢ଼ U+0B5D 
ଡ଼ U+0B5C
ଡ଼ିଡ଼ୁଡ଼ୂଡ଼ୈ
ଢ଼ିଢ଼ୁଢ଼ୂଢ଼ୈ

ଡ଼ U+0B21, U+0B3C
ଢ଼ U+0B22, U+0B3C
ଡ଼ି ଡ଼ୁ ଡ଼ୂ ଡ଼ୈ
ଢ଼ି ଢ଼ୁ ଢ଼ୂ ଢ଼ୈ

**Comment by simoncozens** [comment]
You fixed this - thank you!
