### ISSUE TITLE
Issue with Shape of BA in Conjunct Consonants in NotoSansOriya

### ISSUE THREAD

**Issue by KazunariTsuboi** [notofonts/oriya#22]
### Title
Issue with Shape of BA in Conjunct Consonants in NotoSansOriya

### Font
NotoSansOriya-Regular.ttf

### Where the font came from, and when
Site: https://github.com/notofonts/oriya/releases/tag/NotoSansOriya-v2.005
Date: 2023-03-27

### Font version
Version 2.005

### Issue
The current shape of BA (0B2C) in the sequence of Consonant + halant + BA is undesirable when using NotoSansOriya. It would be more preferable for the glyphs of 0B71, 0B2C, and 0B35 to all have the same shape, similar to what is observed in NotoSerifOriya.

### Character data
କ୍ବ
କ U+0B15 ORIYA LETTER KA
୍ U+0B4D ORIYA SIGN VIRAMA
ବ U+0B2C ORIYA LETTER BA

କ୍ୱ
କ U+0B15 ORIYA LETTER KA
୍ U+0B4D ORIYA SIGN VIRAMA
ୱ U+0B71 ORIYA LETTER WA

କ୍ଵ
କ U+0B15 ORIYA LETTER KA
୍ U+0B4D ORIYA SIGN VIRAMA
ଵ U+0B35 ORIYA LETTER VA

### Screenshot
NotoSansOriya　（Undesirable）
![image](https://github.com/notofonts/oriya/assets/21096794/b8e750d3-0bb4-4d92-8758-8780bd6bece5)

NotoSerifOriya (Desirable）
![image](https://github.com/notofonts/oriya/assets/21096794/43c17ce3-8df9-4277-982d-704fdafef427)

**Comment by simoncozens** [comment]
Looks like you have fixed this as well; thank you!
