### ISSUE TITLE
Troubles with dotted circle

### ISSUE THREAD

**Issue by Mercury13** [notofonts/oriya#24]
### Title 
Two troubles with dotted circle. 1. The character is wider than actual circle (maybe increase circle to the size of actual letter)? 2. Lower umlauts are affixed badly.
### Font
NotoSansOriyaUI-Regular.ttf

### Where the font came from, and when
Site: this repo, beta branch
Date: 2023-06-21

### Font Version
Rev [49c329f](https://github.com/notofonts/oriya/commit/49c329f73f4b5d7f4da30f02cd148c5fba7abca8)

### OS name and version
Win 10, probably all OS

### Application name and version
Qt 6.1.3, probably all apps

### Issue
1. Draw 25CC with some umlaut.
2. Lots of space between circle and umlaut. Umlauts U, Uu, R, Rr, virama hang somewhere else.
3. I think the circle should be bigger (a bit smaller than average letter), and where should those umlauts hang? As those umlauts are primarily affixed to bottom-right, move their anchor ju-ust a bit to the left.

### Character data
U+25CC dotted circle
U+0B3E Oriya vowel sign Aa
U+0B40 Oriya vowel sign Ii
…
U+0B4D Oriya sign Virama
U+0B62 Oriya vowel sign Vocalic L
U+0B63 Oriya vowel sign Vocalic Ll

### Screenshot
![image](https://github.com/notofonts/oriya/assets/10164882/26230fdd-acfd-4aa5-b8dd-751d6ea90f28)
![image](https://github.com/notofonts/oriya/assets/10164882/2a22dec8-1a12-4e4b-907f-0407f8446d47)

**Comment by simoncozens** [comment]
> I think the circle should be bigger (a bit smaller than average letter)

*Maybe*...

> and where should those umlauts hang? As those umlauts are primarily affixed to bottom-right, move their anchor ju-ust a bit to the left.

I'm not convinced. Dotted circle anchors are set programmatically, using the average position of the anchors from the centres of all glyphs, meaning that they end up representative of how the marks are actually used in the font. It's a good way to stop pointless arguments about where dotted anchors should be. ;-)

> NotoSansOriyaUI-Regular.ttf

Sorry, we're not doing more development on the UI fonts. They need to be deprecated and phased out.
