### ISSUE TITLE
Serif: 0B63 has advance width of 508

### ISSUE THREAD

**Issue by Mercury13** [notofonts/oriya#25]
### Title
0B63 has advance width of 508

### Font 
NotoSerifOriya-Regular.ttf

### Where the font came from, and when
Site: notofonts.github.io
Date: 2023-06-26

### Font Version
1.051

### OS name and version
All OS

### Application name and version
All apps

### Issue
1. Write dotted circle + 0B63
2. The pair is too wide
3. The pair should have same width as 25CC+0B62

### Character data
U+0B63 Oriya vowel sign Vocalic Ll

### Screenshot
![image](https://github.com/notofonts/oriya/assets/10164882/161132dd-8332-463c-915e-0edf9947d781)

**Comment by simoncozens** [comment]
This seems fixed (the advance width of the mark is irrelevant, it will get zeroed by the shaping engine):

```
$ shape fonts/NotoSerifOriya/googlefonts/variable/NotoSerifOriya\[wght\].ttf -u 25cc,0b62,25cc,0b63
[uni25CC=0+510|lvocalicvowelsignorya=0@-16,0+0|uni25CC=2+510|llvocalicvowelsignorya=2@-16,0+0]
```
![shape](https://github.com/notofonts/oriya/assets/106728/551816ed-f88c-4b9f-94b1-c6d31c16030a)

**Comment by Mercury13** [comment]
@simoncozens No, someone fixed silently. Build system?
![image](https://github.com/notofonts/oriya/assets/10164882/ea1064bf-5aff-42ee-a7f6-e8361f7c174e)

**Comment by simoncozens** [comment]
Or maybe Kazunari Tsuboi's big PR...

**Comment by Mercury13** [comment]
@simoncozens No, last commit to Serif.glyphs was in March and yours.

**Comment by simoncozens** [comment]
OK, rebuild then. I updated the toolchain because we had pinned some versions to avoid bugs, but the fixes have now been merged in the toolchain repos so we can follow the latest versions again.

**Comment by Mercury13** [comment]
Release version gave this
![image](https://github.com/notofonts/oriya/assets/10164882/a7265cf3-778c-480f-98e1-5cfe7eb8b8a2)
So it’s probably a build system.

**Comment by Mercury13** [comment]
I made working but craggy Nag alphabet before Noto, and right now it has six RLIGs, all related to one issue: prime 1E4ED is a normal spacing character, and letter-prime-letter make overlap between letters. Maybe try to make it a mark having some width?

**Comment by Mercury13** [comment]
@simoncozens So when you make a release someday, state that this issue healed somehow.
