### ISSUE TITLE
Inquiry About Future Updates for Noto Serif Oriya

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/oriya#43]
Hello. Thank you for providing us with great fonts.
I would like to inquire about the future updates for Noto Serif Oriya.
 
Noto Sans Oriya has been updated to version 2.006 and receives updates several times a year.
However, it seems that Noto Serif Oriya has not been updated since version 1.051 was released in 2022.
 
Upon reviewing, I noticed significant differences in the ligature designs between Sans and Serif.

Here are a few examples: କ୍ଷିଙ୍କିଙ୍ଘିଞ୍ଚିଣ୍ଡିନ୍ଦିମ୍ପିତ୍କିଦ୍ଦିଦ୍ଭିସ୍ତ୍ରି
**Sample from Noto Sans Oriya:** 
![スクリーンショット 2024-10-22 153754](https://github.com/user-attachments/assets/be2d6c93-9ce5-43c7-ac39-a8c8a2de014e)
**Sample from Noto Serif Oriya:** 
![スクリーンショット 2024-10-22 153803](https://github.com/user-attachments/assets/3e4cc685-e5c8-424a-bc0b-d98623ddb57f)

I am a bit concerned about the differences in glyphs within the same family.
Could you please let me know if there are any plans for updates? Or should they be considered as separate families?
 
I would greatly appreciate any information you could provide.

**Comment by simoncozens** [comment]
Hello Yusuke! Thank you as always for your interest and support in these fonts.

In an ideal world, all fonts in a Noto family would have the same glyphset and the same engineering. However, in a situation situations like this, achieving the same glyphset would require new glyphs to be drawn; and even though the fonts have different levels of conjunct coverage, they are both basically "working" fonts. This means it is not possible for me to prioritise commissioning new drawings.

So currently there is no plan to update Noto Serif Oriya to the same glyphset as Noto Sans Oriya, and maybe you would be best considering them as separate families.

Of course anyone who wants to contribute new conjuncts to Noto Serif Oriya would be very, very welcome. :-)

**Comment by YusukeShirakihara** [comment]
@simoncozens
Thank you for your prompt response!
I understand the situation well.
We will consider how to proceed together with the local native speakers.
Yusuke
