### ISSUE TITLE
NotoSansOriya does not connect vowels to conjunct consonants

### ISSUE THREAD

**Issue by KazunariTsuboi** [notofonts/oriya#8]
### Font 
NotoSansOriya-*.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/tree/76ab49e/hinted/ttf/NotoSansOriya
Date: 2021-11-02

### Font Version
Version 2.000
commit 76ab49e9a7036b461daec780ae062367473b3ef8

### OS name and version
Windows10 21H2 19044. 1706

### Application name and version
Google Chrome 102.0.5005.63（Official Build） （64 bit）

### Issue
U, UU, R, RR, L, LL cannot be placed correctly on almost every conjunct consonants.

### Character data
କ୍କୁ କ୍କୂ କ୍କୃ କ୍କୄ କ୍କୢ କ୍କୣ

### Screenshot
Here is an example of a string that is having problems.
<img width="548" alt="Vowls" src="https://user-images.githubusercontent.com/21096794/174229443-aea64bf4-94f1-43fc-893c-68a2aa077929.png">

**Comment by simoncozens** [comment]
Bottom anchors are missing on all the conjunct glyphs / "below" components. Adding these would be quite a big job, and would really be better for a designer to do it. It will happen one day but I'm not going to hold up a release for it.

**Comment by simoncozens** [comment]
Looking at this again, adding the anchor is not a big deal. What is a big deal is that in the black and regular weights, the stem width of below conjuncts is much thinner than that of the vowel matras, so we would need to redraw a second set of thin vowel matras:

![shape](https://user-images.githubusercontent.com/106728/220910281-6068deea-c33c-46eb-8d97-6576db0bfb31.png)

Also I noticed that the "nukta" anchors on the conjunct glyphs are in the wrong place.

**Comment by simoncozens** [comment]
This is now fixed, thans to #14! (The variable font is not supporting conjuncts properly due to something wrong with glyphsLib. I'll fix it.)
